<?php 
$itemId = $block->_params['item-id'];
$orderId = $block->_params['order-id'];
$productId = $block->_params['product-id'];
$jsonFilename = $this->getOrderItemString($orderId, $itemId);
$fileContent = $this->pdcHelper->getPDPJsonContent($jsonFilename);
$sidesData = json_decode($fileContent, true);
$mediaUrl = $this->pdcHelper->getMediaUrl() . "pdp/images/";
$orderIncrement = $block->getOrderModel()->load($orderId)->getIncrementId();
$downloadTxtUrl = $this->pdcHelper->getBaseUrl() . "pdc/download/txt/order-id/" . $orderId . "/jsonfile/" . $jsonFilename;
$jsUrl = $this->getPdcJsUrl();
?>
<html>
	<head>
		<title><?php echo 'Order #' . $orderIncrement; echo __(' - Design') ?></title>
        <link rel="stylesheet" href="<?php echo $jsUrl ?>/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?php echo $jsUrl ?>/pace/dataurl.css">
		<link rel="stylesheet" href="<?php echo $jsUrl ?>/fancybox/jquery.fancybox.css">
        <style>
            .pdploading {
                background: rgba(0, 0, 0, 0) url("<?php echo $jsUrl ?>/pdc/images/overlay.png") repeat scroll 0 0;
                height: 100%;
                left: 0;
                opacity: 0.8;
                position: fixed;
                top: 0;
                width: 100%;
                z-index: 999999;
            }
            .pdploading span::after {
                background: rgb(128, 210, 153) none repeat scroll 0 0;
                border-radius: 100% 0;
                bottom: 0;
                color: rgb(255, 255, 255);
                content: "Please wait...";
                font-size: 12px;
                height: 15px;
                left: 0;
                line-height: 15px;
                position: absolute;
                text-indent: 0;
                width: 100%;
                z-index: 1;
            }
            .pdploading span {
                background: rgb(51, 153, 204) url("<?php echo $jsUrl?>/pdc/images/loading.gif") no-repeat scroll center 18px;
                border-radius: 100% 0;
                display: block;
                font-size: 20px;
                height: 70px;
                line-height: 30px;
                margin: 20% auto;
                position: relative;
                text-align: center;
                text-indent: -9999px;
                width: 140px;
                z-index: 9999;
            }
        </style>
	</head>
	<body>
	<?php /* Fix Download */ ?>
		<?php  
			$isNginx = 0;
			$typeServer = $_SERVER["SERVER_SOFTWARE"];
			if($typeServer != '')
			{
				$arTypeSever = explode('/',$typeServer);
				if(isset($arTypeSever[0]) && strtolower($arTypeSever[0]) == 'nginx')
				{
					$isNginx = 1;
				}
			}
		?>
		<div id="pdc-show-link-down" class="pdc-popup" style="display:none;">
		   <p><?php echo __('Please click ') ?><a target="_brank" id="pdc-show-link-down-link" href="#"><?php echo __('Link') ?></a> <?php echo __(' to donwload'); ?>
		</div>
		<input type="hidden" value="<?php echo $this->getUrl(); ?>pdc/index/DownloadAfterCreate" id="link-download-after" name="link_download_after" />
		<input type="hidden" value="<?php echo $isNginx; ?>" id="server-nginx" name="server_nginx" />
		<?php /* end Fix Download */ ?>
		<?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/load_fonts.phtml')->toHtml(); ?>
		<input type="hidden" value="<?php echo htmlentities($fileContent)?>" id="final_design_json"/>
        <input type="hidden" value="<?php echo $jsonFilename ?>" id="json_filename"/>
		<input type="hidden" value="<?php echo $this->pdcHelper->getBaseUrl(); ?>" id="base_url"/>
		<input type="hidden" value="<?php echo $productId ?>" id="product_id"/>
		<input type="hidden" value="<?php echo $orderId ?>" id="order_id"/>
		<input type="hidden" value="<?php echo $itemId ?>" id="item_id"/>
        <input type="hidden" value="<?php echo $orderIncrement ?>" id="increment_id"/>
        <input type="hidden" id="pdp_media_url" name="pdp_media_url" value="<?php echo $mediaUrl ?>" />
		<div class="container">
            <div role="tabpanel">
                <!-- Nav tabs -->
                <ul id="canvas_list" class="nav nav-tabs" role="tablist">
                    <?php $counter = 0; ?>
                    <?php foreach($sidesData as $side) : ?>
                        <?php $tabId = "side_" . $side['id']; ?>
                        <li role="presentation" <?php echo ($counter == 0) ? 'class="active"' : ''; ?>><a href="#<?php echo $tabId ?>" aria-controls="<?php echo $tabId ?>" role="tab" data-toggle="tab"><?php echo $side['label'] ?></a></li>
                        <?php $counter++ ?>
                    <?php endforeach; ?>
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    <?php $counter = 0; ?>
                    <?php foreach($sidesData as $side) : ?>
                        <?php 
                        $tabId = "side_" . $side['id']; 
                        ?>
                        <div role="tabpanel" class="tab-pane <?php echo ($counter == 0) ? 'active' : ''; ?>" id="<?php echo $tabId ?>">
                            <div class="row">
                                <div class="col-md-12 download-btns" style="margin-top: 10px;">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            <?php echo __("DOWNLOAD PDF") ?> <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li><a href="#" pdc-data="pdc-export-btn" pdc-action="DOWNLOAD_PDF_PNG"><?php echo __("PDF contain PNG") ?></a></li>
                                            <li><a href="#" pdc-data="pdc-export-btn" pdc-action="DOWNLOAD_PDF_SVG"><?php echo __("PDF contain SVG") ?></a></li>
                                        </ul>
                                    </div>
                                    <a class="btn btn-primary" pdc-data="pdc-export-btn" pdc-action="DOWNLOAD_SVG"><?php echo __("Download SVG") ?></a>
                                    <a class="btn btn-primary" pdc-data="pdc-export-btn" pdc-action="DOWNLOAD_PNG"><?php echo __("Download PNG") ?></a>
                                    <a class="btn btn-primary" pdc-data="pdc-export-btn" pdc-action="DOWNLOAD_JPG"><?php echo __("Download JPG") ?></a>
                                    <a class="btn btn-primary" href="<?php echo $downloadTxtUrl ?>"><?php echo __("Download TXT") ?></a>
                                    <!--<a class="btn btn-success" pdc-data="pdc-export-btn" pdc-action="DOWNLOAD_ALL"><?php echo __("Download All") ?></a>-->
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-10 canvas-wrapper" style="overflow: auto;">
                                    <canvas style="border: 1px solid #006699; margin: 10px 0px;" id="canvas_<?php echo $tabId ?>" width="<?php echo $side['canvaswidth'] ?>px" height="<?php echo $side['canvasheight'] ?>px" pdc-data='final-canvas'></canvas>
                                </div>
                                <div class="col-md-2 export-options-control" style="text-align: center;">
                                    <ul class="list-group">
                                        <li class="list-group-item">
                                            <span><?php echo __("Include Background") ?></span>
                                            <div class="btn-group" data-toggle="buttons">
                                                <label class="btn btn-success btn-xs active" pdc-data="export-option">
                                                    <input type="radio" name="include_background" value="1" autocomplete="off" checked> <?php echo __("Yes") ?>
                                                </label>
                                                <label class="btn btn-success btn-xs" pdc-data="export-option">
                                                    <input type="radio" name="include_background" value="0" autocomplete="off"> <?php echo __("No") ?>
                                                </label>
                                            </div>
                                        </li>
                                        <li class="list-group-item">
                                            <span><?php echo __("Include Overlay") ?></span>
                                            <div class="btn-group" data-toggle="buttons">
                                                <label class="btn btn-success btn-xs active" pdc-data="export-option">
                                                    <input type="radio" name="include_overlay" value="1" autocomplete="off" checked> <?php echo __("Yes") ?>
                                                </label>
                                                <label class="btn btn-success btn-xs" pdc-data="export-option">
                                                <input type="radio" name="include_overlay" value="0" autocomplete="off"> <?php echo __("No") ?>
                                                </label>
                                            </div>
                                        </li>
                                        <li class="list-group-item">
                                            <span><?php echo __("Edit The Design") ?></span>
                                            <div class="btn-group" data-toggle="buttons">
                                                <label class="btn btn-success btn-xs" pdc-data="export-option">
                                                    <input type="radio" name="edit_design" value="1" autocomplete="off"> <?php echo __("Yes") ?>
                                                </label>
                                                <label class="btn btn-success btn-xs active" pdc-data="export-option">
                                                    <input type="radio" name="edit_design" value="0" autocomplete="off" checked> <?php echo __("No") ?>
                                                </label>
                                            </div>
                                        </li>
                                    </ul>
                                    <a class="btn btn-warning" onclick="window.location.reload();"><?php echo __("Reset") ?></a>
                                </div>
                            </div>
                        </div>
                        <?php $counter++ ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12 well">
                    <strong><?php echo __("NOTE") ?>:</strong>
                    <span><?php echo __("You should have all fonts in Font library installed on your computer to display texts in correct fonts. Please reference document in Fonts section") ?></span>
                </div>
            </div>
        </div>
		<script type="text/javascript" src="<?php echo $jsUrl ?>/jquery/jquery-1.10.2.min.js"></script>
        <script src="<?php echo $jsUrl ?>/bootstrap/js/bootstrap.min.js"></script>
		<?php if($isNginx == 1) : ?>
			<script type="text/javascript" src="<?php echo $jsUrl ?>/fancybox/jquery.fancybox.js"></script>
		<?php endif; ?>
        <script src="<?php echo $jsUrl ?>/pace/pace.min.js"></script>
        <script type="text/javascript" src="<?php echo $jsUrl ?>/fabricjs/fabric.js"></script>
        <script type="text/javascript" src="<?php echo $jsUrl ?>/pdc/js/productsdesignercanvas-1.0.js"></script>
        <script type="text/javascript" src="<?php echo $jsUrl ?>/curvedtext/js/curvedtext.js"></script>
        <script type="text/javascript" src="<?php echo $jsUrl ?>/curvedtext/js/pdc.text.action.js"></script>
        <script type="text/javascript" src="<?php echo $jsUrl ?>/pdc/js/final_design.js"></script>
        <div style="display: none;" class="pdploading"><span><?php echo __("Please wait...") ?></span></div>
	</body>
</html>