<?php 
//$jsUrl = $this->getX3JsUrl(); 
$productConfigsInfo = $this->getProductConfig();
$productConfigs = array();
if(isset($productConfigsInfo['note'])) {
    $productConfigs = $productConfigsInfo['note'];
}
?>
<div class="panel-group panel-mst" id="accordion_app" role="tablist" aria-multiselectable="true">
	<!-- Images -->
	<ul class="nav nav-tabs">
		<?php if(isset($productConfigs['enable_image_plugin']) && $productConfigs['enable_image_plugin'] == 1): ?>
		<li class="active"><a data-toggle="tab" href="#photo"><?php echo __("Clip art") ?></a></li>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_clipart_plugin']) && $productConfigs['enable_clipart_plugin'] == 1): ?>
		<li><a data-toggle="tab" href="#clipart"><?php echo __("Photos") ?></a></li>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_shape_plugin']) && $productConfigs['enable_shape_plugin'] == 1): ?>
		<li><a data-toggle="tab" href="#shapes"><?php echo __("Shapes") ?></a></li>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_frame_plugin']) && $productConfigs['enable_frame_plugin'] == 1): ?>
		<li><a data-toggle="tab" href="#frames"><?php echo __("Mask") ?></a></li>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_qrcode_plugin']) && $productConfigs['enable_qrcode_plugin'] == 1): ?>
		<li><a data-toggle="tab" href="#qrcode"><?php echo __("QR Code") ?></a></li>
		<?php endif; ?>
	</ul>
	<div class="tab-content">
		<?php if(isset($productConfigs['enable_image_plugin']) && $productConfigs['enable_image_plugin'] == 1): ?>
		<div id="photo" class="tab-pane fade in active">
			<div class="pdc-show-content"> 
            	<?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/image.phtml')->toHtml(); ?>
			</div>
		</div>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_clipart_plugin']) && $productConfigs['enable_clipart_plugin'] == 1): ?>
		<div id="clipart" class="tab-pane">
			<div class="pdc-show-content" pdc-image-type="clipart">
				<div class="loading-image" style="display: none;"><?php echo __("Loading...") ?></div>
				<div class="image-container" style="display: none;">
					<div class="select-cont">
						<select pdc-data="pdc-image-category">

						</select>
						<span class="fake-select"><i class="fa fa-caret-down"></i></span>
					</div>
					<div class="no-image-item" style="display: none;">
						<?php echo __("There is no item on this category!") ?>
					</div>
					<ul class="items-list" pdc-data="image-list">

					</ul>
					<div class="load-more-wrapper">
						<button style="display: none;" class="btn btn-info btn-sm" pdc-data="load-more-image" type="button" ><?php echo __("Load More")?></button>
					</div>
				</div>
				<div class="no-item">
					<?php echo __("There is no item yet. Please use upload plugin instead!") ?>
				</div>
			</div>
		</div>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_shape_plugin']) && $productConfigs['enable_shape_plugin'] == 1): ?>
		<div id="shapes" class="tab-pane">
			<div class="pdc-show-content" pdc-image-type="shape">
				<div class="loading-image" style="display: none;"><?php echo __("Loading...") ?></div>
				<div class="image-container" style="display: none;">
					<div class="select-cont">
						<select pdc-data="pdc-image-category">

						</select>
						<span class="fake-select"><i class="fa fa-caret-down"></i></span>
					</div>
					<div class="no-image-item" style="display: none;">
						<?php echo __("There is no item on this category!") ?>
					</div>
					<ul class="items-list" pdc-data="image-list">

					</ul>
					<div class="load-more-wrapper">
						<button style="display: none;" class="btn btn-info btn-sm" pdc-data="load-more-image" type="button" ><?php echo __("Load More")?></button>
					</div>
				</div>
				<div class="no-item">
					<?php echo __("There is no item yet. Please use upload plugin instead!") ?>
				</div>
			</div>
		</div>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_frame_plugin']) && $productConfigs['enable_frame_plugin'] == 1): ?>
		<div id="frames" class="tab-pane">
			<div class="pdc-show-content" pdc-image-type="frame">
				<div class="loading-image" style="display: none;"><?php echo __("Loading...") ?></div>
				<div class="image-container" style="display: none;">
					<div class="select-cont">
						<select pdc-data="pdc-image-category">

						</select>
						<span class="fake-select"><i class="fa fa-caret-down"></i></span>
					</div>
					<div class="no-image-item" style="display: none;">
						<?php echo __("There is no item on this category!") ?>
					</div>
					<ul class="items-list" pdc-data="image-list">
						<!--<li rel="no-frame"><img src="<?php //echo $jsUrl ?>images/no-frame.png" alt="No Frame" object-type="frame"/></li>-->
					</ul>
					<div class="load-more-wrapper">
						<button style="display: none;" class="btn btn-info btn-sm" pdc-data="load-more-image" type="button" ><?php echo __("Load More")?></button>
					</div>
				</div>
				<div class="no-item">
					<?php echo __("There is no frame!") ?>
				</div>
			</div>
		</div>
		<?php endif; ?>
		<?php if(isset($productConfigs['enable_qrcode_plugin']) && $productConfigs['enable_qrcode_plugin'] == 1): ?>
		<div id="qrcode" class="tab-pane">
			<div class="pdc-show-content">
				<!--div class="gallery-trigger-close close">x</div>													
				<h3 class="title"><span><?php echo __("Sign your design with a QR Code (?)") ?></span></h3-->
				<div class="pdc-show-content-detail">
					<!-- Nav tabs -->
					<ul class="nav nav-tabs" role="tablist">
						<li role="presentation" class="active">
							<a href="#qrcode_url" aria-controls="qrcode_url" role="tab" data-toggle="tab"><i class="fa  fa-link"></i> <?php echo __("URL") ?></a>
						</li>
						<li role="presentation">
							<a href="#qrcode_text" aria-controls="qrcode_text" role="tab" data-toggle="tab"><i class="fa fa-paragraph"></i> <?php echo __("Text") ?></a>
						</li>
						<li role="presentation">
							<a href="#qrcode_email" aria-controls="qrcode_email" role="tab" data-toggle="tab"><i class="fa fa-envelope-square"></i> <?php echo __("Email") ?></a>
						</li>
						<li role="presentation">
							<a href="#qrcode_phone" aria-controls="qrcode_phone" role="tab" data-toggle="tab"><i class="fa fa-mobile"></i> <?php echo __("Phone") ?></a>
						</li>
					</ul>

					<!-- Tab panes -->
					<div class="tab-content">
						<div role="tabpanel" class="tab-pane active qrcode-type" id="qrcode_url">
							<div class="top-pane">
								<input type="input" placeholder="<?php echo __("Website (URL). Eg: http://www.example.com");?>"/>
							</div>
							<div class="main-pane">
								<button class="pdc-btn gene-qrcode-btn" type="button"><span><?php echo __("GENERATE QR CODE") ?></span></button>
							</div>

						</div>
						<div role="tabpanel" class="tab-pane qrcode-type" id="qrcode_text">
							<div class="top-pane">
								<input type="input" placeholder="<?php echo __("Enter your text");?>"/>
							</div>
							<div class="main-pane">
								<button class="pdc-btn gene-qrcode-btn" type="button"><span><?php echo __("GENERATE QR CODE") ?></span></button>
							</div>
						</div>
						<div role="tabpanel" class="tab-pane qrcode-type" id="qrcode_email">
							<div class="top-pane">
								<input type="input" placeholder="<?php echo __("Your email address");?>"/>
							</div>
							<div class="main-pane">
								<button class="pdc-btn gene-qrcode-btn" type="button"><span><?php echo __("GENERATE QR CODE") ?></span></button>
							</div>
						</div>
						<div role="tabpanel" class="tab-pane qrcode-type" id="qrcode_phone">
							<div class="top-pane">
								<input type="input" placeholder="<?php echo __("Enter phone number");?>"/>
							</div>
							<div class="main-pane">
								<button class="pdc-btn gene-qrcode-btn" type="button"><span><?php echo __("GENERATE QR CODE") ?></span></button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<?php endif; ?>
	</div>
</div>