<?php 
$productConfigsInfo = $this->getProductConfig();
$productConfigs = array();
if(isset($productConfigsInfo['note'])) {
    $productConfigs = $productConfigsInfo['note'];
}
$productId = $this->getCurrentProductId();
$productColors = $this->pdcHelper->getProductDesignColors($productId);
$isProductColorTabEnable = $this->pdcHelper->isProductColorTabEnable($productColors);
$bgActive = $productColorActive = $templateActive = "";
if($isProductColorTabEnable) {
    $productColorActive = "active";
    if($this->isShowTemplateTab()) {
        $productColorActive = "";
        $templateActive = "active";
    }
} else {
    $bgActive = "active";
}
?>
<div id="p-design-tab">
	<div class="panel-group panel-mst" id="accordion_design" role="tablist" aria-multiselectable="true">
		<ul class="nav nav-tabs">
			<?php if($this->isShowTemplateTab()) : ?>
			<li class="active"><a data-toggle="tab" href="#templates"><?php echo __("Templates") ?></a></li>
			<?php endif; ?>
			<?php if(isset($productConfigs['enable_background_plugin']) && $productConfigs['enable_background_plugin'] == 1): ?>
			<li><a data-toggle="tab" href="#background"><?php echo __("Background") ?></a></li>
			<?php endif; ?>
			<?php if($isProductColorTabEnable): ?>
			<li><a data-toggle="tab" href="#productColor"><?php echo __("Product Colors") ?></a></li>
			<?php endif; ?>
		</ul>
		<div class="tab-content">
			<?php if($this->isShowTemplateTab()) : ?>
			<div id="templates" class="tab-pane fade in active">
				<div class="pdc-show-content">
					<?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/templates.phtml')->toHtml(); ?>
				</div>
			</div>
			<?php endif; ?>
			<?php if(isset($productConfigs['enable_background_plugin']) && $productConfigs['enable_background_plugin'] == 1): ?>
			<div id="background" class="tab-pane">
				<div class="pdc-show-content">
					<?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/background.phtml')->toHtml(); ?>
				</div>
			</div>
			<?php endif; ?>
			<?php if($isProductColorTabEnable): ?>
			<div id="productColor" class="tab-pane">
				<div class="pdc-show-content">
					<?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/productcolor.phtml')->toHtml(); ?>
				</div>
			</div>
			<?php endif; ?>
	</div>
</div>
