<script>
    requirejs([
        'jquery',
        'colorpicker'
    ], function($){
        $('#block_color_code').ColorPicker({
            onShow: function (colpkr) {
                $(colpkr).fadeIn(500);
                return false;
            },
            onHide: function (colpkr) {
                $(colpkr).fadeOut(500);
                return false;
            },
            onChange: function (hsb, hex, rgb) {
                $('#block_color_code').val(hex).css('backgroundColor', '#' + hex);
            }
        });  
    });
</script>