<?php $jsUrl = $this->getPdcJsUrl(); ?>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="<?php echo $jsUrl ?>/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo $jsUrl ?>/bootstrap/css/bootstrap.vertical-tabs.css">
<link rel="stylesheet" href="<?php echo $jsUrl ?>/x3/css/imagelistexpander.css" />
<link rel="stylesheet" href="<?php echo $jsUrl ?>/scrollbar/jquery.scrollbar.css" />
<link rel="stylesheet" href="<?php echo $jsUrl ?>/x3/css/pdc-x3.css">

<link rel="stylesheet" type="text/css" media="only screen and (max-width: 339px)" href="<?php echo $jsUrl ?>/x3/css/mobile-320.css" />
<link rel="stylesheet" type="text/css" media="only screen and (min-width: 340px) and (max-width: 767px)" href="<?php echo $jsUrl ?>/x3/css/mobile-480.css" />
<link rel="stylesheet" type="text/css" media="screen and (min-width: 768px) and (max-width: 1023px)" href="<?php echo $jsUrl ?>/x3/css/tablet-768.css" />
<link rel="stylesheet" type="text/css" media="screen and (min-width: 1024px) and (max-width: 1260px)" href="<?php echo $jsUrl ?>/x3/css/laptop-1024.css" />
<!-- Add fancyBox main JS and CSS files -->
<link rel="stylesheet" type="text/css" href="<?php echo $jsUrl ?>/fancybox/jquery.fancybox.css" media="screen" />
<!-- Optional theme -->
<link rel="stylesheet" href="<?php echo $jsUrl ?>/bootstrap/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="<?php echo $jsUrl ?>/font-awesome-4.4.0/css/font-awesome.min.css">

<link href="<?php echo $jsUrl ?>/pdc/css/pdc.layer.css" rel="stylesheet"/>