<?php 
$jsUrl = $this->getX3JsUrl();
$limit = $this->_default_page_size;
$categories = $this->getAllImageCategories();
$productId = $this->getCurrentProductId();
$isProductColorTabEnable = $this->pdcHelper->isProductColorTabEnable($productId);
$productConfigsInfo = $this->getProductConfig();
$productConfigs = array();
if(isset($productConfigsInfo['note'])) {
    $productConfigs = $productConfigsInfo['note'];
}
?>
<input type="hidden" value='<?php echo $limit;?>'  id="default_page_size" />
<input type="hidden" value='<?php echo htmlentities($categories);?>' id="pdc-image-categories" />
<div class="pdc-tabs">
    <!-- Nav tabs -->
    <div class="nav nav-tabs tabs-left">
        <?php if(isset($productConfigs['enable_elements_tab']) && $productConfigs['enable_elements_tab'] == 1): ?>
                <a class="a-apps" href="#apps" data-toggle="accordion" data-group-target="left-area"><?php echo __("Elements") ?></a>
                <div class="accordion-pane" id="apps" data-group="left-area">
                    <div class="title hidden-md hidden-lg"><h3><?php echo __("Elements") ?></h3><a href="#" class="close-bt"></a></div>
                    <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/app.phtml')->toHtml(); ?>																				
                </div>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_upload_tab']) && $productConfigs['enable_upload_tab'] == 1): ?>
                <a class="a-upload" href="#upload" data-toggle="accordion" data-group-target="left-area"><?php echo __("Uploads") ?></a>
                <div class="accordion-pane" id="upload" data-group="left-area">
                    <div class="title hidden-md hidden-lg"><h3><?php echo __("Uploads") ?></h3><a href="#" class="close-bt"></a></div>
                    <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/product_upload.phtml')->toHtml(); ?>																				
                </div>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_text_tab']) && $productConfigs['enable_text_tab'] == 1): ?>
                <a class="a-text" href="#text" data-toggle="accordion" data-group-target="left-area"><?php echo __("Text") ?></a>
                <div class="accordion-pane" id="text" data-group="left-area">
                    <div class="title hidden-md hidden-lg"><h3><?php echo __("Text") ?></h3><a href="#" class="close-bt"></a></div>
                    <div class="textControls">
                        <p><?php echo __('Click to add text');?></p>
                        <ul>
                            <li>
                                <a pdc-data="add-text" fontsize="72" style=" font-size: 180%; font-style: normal; font-weight: 600;" data-style="title" class="add-text"><?php echo __('Add heading');?></a>
                            </li>
                            <li style="margin:6px 0 11px;">
                                <a pdc-data="add-text" fontsize="36" style=" font-size: 140%; font-style: normal; font-weight: normal;" data-style="subtitle" class="add-text"><?php echo __('Add subheading');?></a>
                            </li>
                            <li>
                                <a pdc-data="add-text" fontsize="24" style="font-size: 100%; font-style: normal; font-weight: normal;" data-style="body" class="add-text"><?php echo __('Add a little bit of body text');?></a>
                            </li>
                        </ul>
                    </div>
                    <div class="curved-text-wrapper">
                        <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/curvedtext.phtml')->toHtml(); ?>
                    </div>
                </div>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_layer_tab']) && $productConfigs['enable_layer_tab'] == 1): ?>
                <a class="a-layers" href="#layers" data-toggle="accordion" data-group-target="left-area"><?php echo __("Layers") ?></a>
                <div class="accordion-pane" id="layers" data-group="left-area">
                    <div class="title hidden-md hidden-lg"><h3><?php echo __("Layers") ?></h3><a href="#" class="close-bt"></a></div>
                    <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/layer.phtml')->toHtml(); ?>
                </div>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_product_design_tab']) && $productConfigs['enable_product_design_tab'] == 1): ?>
                <a class="a-product-design" href="#productDesign" data-toggle="accordion" data-group-target="left-area"><?php echo __("Product") ?></a>
                <div class="accordion-pane" id="productDesign" data-group="left-area">
                    <div class="title hidden-md hidden-lg"><h3><?php echo __("Product") ?></h3><a href="#" class="close-bt"></a></div>
                    <?php echo $this->getLayout()->createBlock('Magebay\Pdc\Block\X3')->setTemplate('Magebay_Pdc::x3/design/left-area/product_design.phtml')->toHtml(); ?>																			
                </div>
		<?php endif; ?>
        <?php if(isset($productConfigs['enable_info_tab']) && $productConfigs['enable_info_tab'] == 1): ?>
                <a class="a-info" href="#info" data-toggle="accordion" data-group-target="left-area"><?php echo __("Info") ?></a>
                <div class="accordion-pane" id="info" data-group="left-area">
                    <div class="title hidden-md hidden-lg"><h3><?php echo __("Info") ?></h3><a href="#" class="close-bt"></a></div>
                    <div class="pdc-show-content">
                        <?php $productData = $this->getProductInfo(); ?>
                        <?php echo isset($productData['short_description']) ? $productData['short_description'] : '';  ?>
                    </div>
                </div>
        <?php endif; ?>
        <?php if(isset($productConfigs['enable_zoom_btn']) && $productConfigs['enable_zoom_btn'] == 1): ?>
        <!--
		<div>
			<div class="pdc-zoom hidden-md hidden-lg">
				<button type="button" class="btn-zoom btn-zoom-in"><span><i class="fa fa-search-plus"></i> <?php echo __('Zoom In');?></span></button>
				<input type="text" disabled="disabled" class="input-zoom" value="100%"/>
				<button type="button" class="btn-zoom btn-zoom-out"><span><i class="fa fa-search-minus"></i> <?php echo __('Zoom Out');?></span></button>
				<button type="button" class="btn-zoom btn-zoom-reset"><span><i class="fa fa-compress"></i> <?php echo __('Reset');?></span></button>
			</div>
		</div>
        -->
        <?php endif; ?>
    </div>
</div>