<!--	Save Popup		-->
<div id="pdc-save-cont" class="pdc-popup" style="display:none;">
    <h3 class="title"><?php echo __("Login to continue save the customized design") ?></h3>
    <form class="form-horizontal" id="pdp-login-form" url="<?php echo $this->pdcHelper->getBaseUrl().'pdc/index/login' ?>">
        <input type="hidden" id="is_customer_logged" value="<?php echo $this->isLoggedIn() ?>" />
        <div class="form-group">
            <label for="username" class="col-sm-6 col-lg-5 control-label"><?php echo __("Username") ?>(*)</label>
            <div class="col-sm-6 col-lg-7">
              <input type="text" class="form-control required-entry" id="username" name="login[username]" placeholder="Username">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-6 col-lg-5 control-label"><?php echo __("Password") ?>(*)</label>
            <div class="col-sm-6 col-lg-7">
              <input type="password" class="form-control required-entry" id="inputPassword3" name="login[password]" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-7 col-sm-6 form-gr-login">
                <button class="pdc-btn pdc-btn-green pdc-login bt-pdp-login-1"><span><img src="<?php echo $this->pdcHelper->getMediaUrl() . 'pdp/images/ajax-loader.gif';?>" /></span></button>
                <i><p><a class="a-link-green" target="_blank" href="<?php echo $this->pdcHelper->getBaseUrl() ?>customer/account/forgotpassword/"><?php echo __("Forgot your password?") ?></a></p></i>
                <button type="button" pdc-data="customer-login" class="pdc-btn pdc-btn-green pdc-login bt-pdp-login-2"><span><?php echo __("Login") ?></span></button>
            </div>
        </div>
        <div class="form-group form-gr-btm">
            <div class="col-lg-6 col-sm-6">
                <a href="<?php echo $this->pdcHelper->getBaseUrl() ?>customer/account/create/" target="_blank" class="pdc-btn pdc-continue-guest"><span<?php echo __(">Create an Account") ?></span></a>
            </div>
            <div class="col-lg-6 col-sm-6">
              <button type="button" pdc-data="SAVE_GUEST_DESIGN" class="pdc-btn pdc-continue-guest"><span><?php echo __("CONTINUE AS GUEST") ?></span></button>
            </div>
        </div>
    </form>			
</div>
<!--	Reset Popup		-->
<div id="pdc-reset-cont" class="pdc-popup" style="display:none;">
    <p class="col-lg-12"><?php echo __("This action will clear all customized design. Are you sure") ?>?</p>
    <ul>
        <li class="col-lg-6 col-sm-6 col-xs-6"><a href="#" class="pdc-btn reset" pdc-data="RESET_DESIGN"><span><?php echo __("OK, RESET DESIGN") ?></span></a></li>
        <li class="col-lg-6 col-sm-6 col-xs-6"><a href="#" class="pdc-btn cancel pdc-close-popup pdc-btn-red"><span><?php echo __("Cancel") ?></span></a></li>
    </ul>
</div>
<!-- Close Popup -->
<div id="pdc-close-cont" class="pdc-popup" style="display:none;">
    <p class="col-lg-12"><?php echo __("Do you want to save your customized design?") ?></p>
    <ul>
        <li class="col-lg-6 col-sm-6  col-xs-6"><a href="javascript:void(0);" pdc-data="SAVE_DESIGN_BEFORE_CLOSE" class="pdc-btn"><span><?php echo __("OK, Save My Design") ?></span></a></li>
        <li class="col-lg-6 col-sm-6  col-xs-6"><a href="javascript:void(0);" pdc-data="CLOSE_DESIGN_WITHOUT_SAVE" class="pdc-btn pdc-btn-red"><span><?php echo __("Close") ?> </span></a></li>
    </ul>
</div>
<!--	Share Popup		-->
<div id="pdc-share-cont" class="pdc-popup" style="display:none;">
    <h3 class="title"><?php echo __("Share the customized design to your friends") ?></h3>
    <div class="share-info">
        <div class="col-lg-5 img-left"><img src="" alt="" /></div>
        <div class="col-lg-7 cont-right">
            <span class="title"><?php echo __("Summer DEALSL") ?></span>
            <a href="#" class="link" target="_blank">http://www.yoursite.com/index.php/pdc/customize/id/1987/00/</a>
            <span class="des"><?php echo __("Lorem Ipsum is simply dummy text of the printing and typesetting industry.") ?>  </span>
        </div>
    </div>
    <!--ul class="share-btn-list">
        <li class="col-lg-6"><a href="#" class="pdc-btn share-face pdc-btn-blue"><span>Share on Facebook</span></a></li>
        <li class="col-lg-6"><a href="#" class="pdc-btn share-twitter"><span>Share on Twitter</span></a></li>
        <li class="col-lg-6"><a href="#" class="pdc-btn share-google-plus pdc-btn-red"><span>Share on Google Plus</span></a></li>
        <li class="col-lg-6"><a href="#" class="pdc-btn share-instagram pdc-btn-orange"><span>Share on Instagram</span></a></li>
    </ul-->
    <div class="share-btn-list">  
        <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
            <li class="col-lg-6 col-sm-6"><a class="addthis_button_facebook pdc-btn pdc-btn-blue"><?php echo __("Share on Facebook") ?></a></li>
            <li class="col-lg-6 col-sm-6"><a class="addthis_button_twitter pdc-btn share-twitter"><?php echo __("Share on Twitter") ?></a></li>
            <!--li class="col-lg-6"><a class="addthis_button_pinterest_share pdc-btn share-instagram pdc-btn-orange">Share on Pinterest</a></li-->
            <li class="col-lg-6 col-sm-6"><a class="addthis_button_google_plusone_share pdc-btn pdc-btn-red"><?php echo __("Share on Google Plus") ?></a></li>
            <li class="col-lg-6 col-sm-6"><a class="addthis_button_email pdc-btn pdc-btn-gray"><?php echo __("Share on Email") ?></a></li>
        </div>
    </div>
    <div class="pinterest-share-thumbnail" style="position: absolute; top: -100000px; right: 100000px"></div>
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5099b58f632bd3db"></script>
</div>
<!--	Save Details Popup		-->
<div id="pdc-show-link-down" class="pdc-popup" style="display:none;">
   <p><?php echo __('Please click ') ?><a target="_brank" id="pdc-show-link-down-link" href="#"><?php echo __('Link') ?></a> <?php echo __(' to donwload'); ?>
</div>
<?php if($this->pdcHelper->isLoggedIn() && $this->pdcHelper->getStoreConfigData("pdp/customer_action/design_details") == "1") : ?>
<div id="pdc-save-design-details" class="pdc-popup" style="display:none;">
    <h3 class="title"><?php echo __("Design Details") ?></h3>
    <form class="form-horizontal" id="pdp-save-design-details">
        <div class="form-group">
            <label for="design_title" class="col-sm-6 col-lg-3 control-label"><?php echo __("Design Name") ?></label>
            <div class="col-sm-6 col-lg-9">
              <input type="text" class="form-control" id="design_title" name="design[title]" placeholder="<?php echo __("Enter design name") ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="design_note" class="col-sm-6 col-lg-3 control-label"><?php echo __("Design Description") ?></label>
            <div class="col-sm-6 col-lg-9">
                <textarea class="form-control" id="design_note" name="design[note]" placeholder="<?php echo __("Note for later use") ?>"></textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-12 col-sm-6">
                <button type="button" pdc-data="SAVE_CUSTOMER_DESIGN_DETAILS" class="pdc-btn pdc-btn-green"><span><?php echo __("Save And Continue") ?></span></button>
            </div>
        </div>
    </form>			
</div>
<?php endif; ?>